name: Bug Report
description: Report a bug
title: "[Bug] "
labels: [ "bug" ]
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: A clear and concise description of the bug.
  validations:
    required: true
- type: input
  id: software-tools
  attributes:
    label: Software/Tools
    description: Specify the software/tools (e.g., Ansible 1.17).
    placeholder: "Ansible 2.17"
  validations:
    required: true
- type: input
  id: os
  attributes:
    label: OS
    description: Specify the operating system (e.g., Ubuntu 22.04).
    placeholder: "Ubuntu 22.04"
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: |
      1. Describe the setup (e.g., inventory.yaml).
      2. Run the specific command, script, or process.
      3. Observe the error or unexpected behavior.
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: What should happen?
  validations:
    required: true
- type: textarea
  id: actual-behavior
  attributes:
    label: Actual Behavior
    description: What is happening?
  validations:
    required: true
- type: textarea
  id: screenshots-logs
  attributes:
    label: Screenshots/Logs
    description: Add error logs, screenshots, or configuration files if applicable.
