---
# Install docker and initialize the swarm
- name: Setup docker-swarm master
  hosts: proxy
  become: true
  roles:
  - role: install
  - role: docker_swarm_master

- name: Setup docker-swarm worker
  hosts:
  - storage
  - web
  - auth
  become: true
  roles:
  - role: install
  - role: docker_swarm_worker

# Add qasmatuser, directories, node labels, secrets and configs
- name: Add directories, permissions and node labels
  hosts:
  - proxy
  - storage
  - web
  become: true
  roles:
  - role: add_qasmatuser_dir
  - role: add_nodelabels

- name: Add secrets
  hosts: proxy
  become: true
  roles:
  - role: add_secrets

- name: Add qasmat config
  hosts:
  - proxy
  - storage
  become: true
  roles:
  - role: add_qasmat_config

- name: Add web config
  hosts: web
  become: true
  roles:
  - role: add_web_config

- name: Load ssl certificates
  hosts: web
  become: true
  roles:
  - role: restore_cert
    when:
    - backup_data is defined and (backup_data | default('', true) | length > 0)

# Pull docker images and deploy the stack
- name: Pull docker_images
  hosts:
  - proxy
  - storage
  - web
  become: true
  roles:
  - role: docker_login_pull

- name: Deploy the Web Client Stack
  hosts: "{{ groups['proxy'][0] }}"
  become: true
  roles:
  - role: web_client_deploy

- name: Deploy and configure Keycloak (conditional)
  hosts: keycloak
  become: true
  roles:
  - role: keycloak
    when:
    - keycloak_dns is defined and (keycloak_dns | default('', true) | length > 0)

- name: Deploy the docker-swarm stack
  hosts: "{{ groups['proxy'][0] }}"
  become: true
  roles:
  - role: docker_swarm_deploy
